### ISSUE TITLE
Tests fail with perls < 5.22.0

### ISSUE THREAD

**Issue by andk** [Leont/crypt-passphrase#2]
Sample fail report: http://www.cpantesters.org/cpan/report/104b0c52-d24d-11ed-be7f-f3db6d8775ea

Bisect leads me to the commit 

commit e660c409f22c1a7f1be06f3ef5168a7a09a5835a
Author: Father Chrysostomos <sprout@cpan.org>
Date:   Tue Oct 28 16:52:18 2014 -0700

    [perl #122782] map{no strict;...} etc.

Older perls need something like

% /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.20.3/1e0c/bin/perl -le 'print join ",", sort { sub { no strict; $a <=> $b }->() } 1,2,3,10,10,3,2,1 '
1,1,2,2,3,3,10,10

**Comment by Leont** [comment]
Thanks for the report. Fixed in version 0.015
